// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonGiftConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CommonGiftConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CommonGiftConfig {

namespace {

const ::google::protobuf::Descriptor* BaseItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BaseItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* PropsItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PropsItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommonModifyItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonModifyItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommonModifyItemRate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonModifyItemRate_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommonModifyItemGrow_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonModifyItemGrow_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommonModifyItemNormal_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonModifyItemNormal_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommonModifyItemSimple_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommonModifyItemSimple_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CommonGiftConfig_2eproto() {
  protobuf_AddDesc_CommonGiftConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CommonGiftConfig.proto");
  GOOGLE_CHECK(file != NULL);
  BaseItem_descriptor_ = file->message_type(0);
  static const int BaseItem_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, coin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, cash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, exp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, friend__),
  };
  BaseItem_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BaseItem_descriptor_,
      BaseItem::default_instance_,
      BaseItem_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseItem, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BaseItem));
  PropsItem_descriptor_ = file->message_type(1);
  static const int PropsItem_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropsItem, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropsItem, count_),
  };
  PropsItem_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PropsItem_descriptor_,
      PropsItem::default_instance_,
      PropsItem_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropsItem, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropsItem, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PropsItem));
  CommonModifyItem_descriptor_ = file->message_type(2);
  static const int CommonModifyItem_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItem, based_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItem, props_),
  };
  CommonModifyItem_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonModifyItem_descriptor_,
      CommonModifyItem::default_instance_,
      CommonModifyItem_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItem, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItem, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonModifyItem));
  CommonModifyItemRate_descriptor_ = file->message_type(3);
  static const int CommonModifyItemRate_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemRate, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemRate, rate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemRate, item_),
  };
  CommonModifyItemRate_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonModifyItemRate_descriptor_,
      CommonModifyItemRate::default_instance_,
      CommonModifyItemRate_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemRate, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemRate, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonModifyItemRate));
  CommonModifyItemGrow_descriptor_ = file->message_type(4);
  static const int CommonModifyItemGrow_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemGrow, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemGrow, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemGrow, item_),
  };
  CommonModifyItemGrow_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonModifyItemGrow_descriptor_,
      CommonModifyItemGrow::default_instance_,
      CommonModifyItemGrow_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemGrow, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemGrow, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonModifyItemGrow));
  CommonModifyItemNormal_descriptor_ = file->message_type(5);
  static const int CommonModifyItemNormal_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemNormal, item_),
  };
  CommonModifyItemNormal_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonModifyItemNormal_descriptor_,
      CommonModifyItemNormal::default_instance_,
      CommonModifyItemNormal_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemNormal, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemNormal, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonModifyItemNormal));
  CommonModifyItemSimple_descriptor_ = file->message_type(6);
  static const int CommonModifyItemSimple_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemSimple, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemSimple, item_),
  };
  CommonModifyItemSimple_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CommonModifyItemSimple_descriptor_,
      CommonModifyItemSimple::default_instance_,
      CommonModifyItemSimple_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemSimple, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommonModifyItemSimple, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CommonModifyItemSimple));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CommonGiftConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BaseItem_descriptor_, &BaseItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PropsItem_descriptor_, &PropsItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonModifyItem_descriptor_, &CommonModifyItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonModifyItemRate_descriptor_, &CommonModifyItemRate::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonModifyItemGrow_descriptor_, &CommonModifyItemGrow::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonModifyItemNormal_descriptor_, &CommonModifyItemNormal::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CommonModifyItemSimple_descriptor_, &CommonModifyItemSimple::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CommonGiftConfig_2eproto() {
  delete BaseItem::default_instance_;
  delete BaseItem_reflection_;
  delete PropsItem::default_instance_;
  delete PropsItem_reflection_;
  delete CommonModifyItem::default_instance_;
  delete CommonModifyItem_reflection_;
  delete CommonModifyItemRate::default_instance_;
  delete CommonModifyItemRate_reflection_;
  delete CommonModifyItemGrow::default_instance_;
  delete CommonModifyItemGrow_reflection_;
  delete CommonModifyItemNormal::default_instance_;
  delete CommonModifyItemNormal_reflection_;
  delete CommonModifyItemSimple::default_instance_;
  delete CommonModifyItemSimple_reflection_;
}

void protobuf_AddDesc_CommonGiftConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026CommonGiftConfig.proto\022\020CommonGiftConf"
    "ig\"C\n\010BaseItem\022\014\n\004coin\030\001 \001(\005\022\014\n\004cash\030\002 \001"
    "(\005\022\013\n\003exp\030\003 \001(\005\022\016\n\006friend\030\004 \001(\005\"&\n\tProps"
    "Item\022\n\n\002id\030\001 \002(\r\022\r\n\005count\030\002 \002(\005\"i\n\020Commo"
    "nModifyItem\022)\n\005based\030\001 \001(\0132\032.CommonGiftC"
    "onfig.BaseItem\022*\n\005props\030\002 \003(\0132\033.CommonGi"
    "ftConfig.PropsItem\"b\n\024CommonModifyItemRa"
    "te\022\n\n\002id\030\001 \002(\r\022\014\n\004rate\030\002 \002(\r\0220\n\004item\030\003 \002"
    "(\0132\".CommonGiftConfig.CommonModifyItem\"c"
    "\n\024CommonModifyItemGrow\022\n\n\002id\030\001 \002(\r\022\r\n\005le"
    "vel\030\002 \002(\r\0220\n\004item\030\003 \002(\0132\".CommonGiftConf"
    "ig.CommonModifyItem\"J\n\026CommonModifyItemN"
    "ormal\0220\n\004item\030\001 \002(\0132\".CommonGiftConfig.C"
    "ommonModifyItem\"V\n\026CommonModifyItemSimpl"
    "e\022\n\n\002id\030\001 \002(\r\0220\n\004item\030\002 \002(\0132\".CommonGift"
    "Config.CommonModifyItem", 623);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CommonGiftConfig.proto", &protobuf_RegisterTypes);
  BaseItem::default_instance_ = new BaseItem();
  PropsItem::default_instance_ = new PropsItem();
  CommonModifyItem::default_instance_ = new CommonModifyItem();
  CommonModifyItemRate::default_instance_ = new CommonModifyItemRate();
  CommonModifyItemGrow::default_instance_ = new CommonModifyItemGrow();
  CommonModifyItemNormal::default_instance_ = new CommonModifyItemNormal();
  CommonModifyItemSimple::default_instance_ = new CommonModifyItemSimple();
  BaseItem::default_instance_->InitAsDefaultInstance();
  PropsItem::default_instance_->InitAsDefaultInstance();
  CommonModifyItem::default_instance_->InitAsDefaultInstance();
  CommonModifyItemRate::default_instance_->InitAsDefaultInstance();
  CommonModifyItemGrow::default_instance_->InitAsDefaultInstance();
  CommonModifyItemNormal::default_instance_->InitAsDefaultInstance();
  CommonModifyItemSimple::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CommonGiftConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CommonGiftConfig_2eproto {
  StaticDescriptorInitializer_CommonGiftConfig_2eproto() {
    protobuf_AddDesc_CommonGiftConfig_2eproto();
  }
} static_descriptor_initializer_CommonGiftConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int BaseItem::kCoinFieldNumber;
const int BaseItem::kCashFieldNumber;
const int BaseItem::kExpFieldNumber;
const int BaseItem::kFriendFieldNumber;
#endif  // !_MSC_VER

BaseItem::BaseItem()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.BaseItem)
}

void BaseItem::InitAsDefaultInstance() {
}

BaseItem::BaseItem(const BaseItem& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.BaseItem)
}

void BaseItem::SharedCtor() {
  _cached_size_ = 0;
  coin_ = 0;
  cash_ = 0;
  exp_ = 0;
  friend__ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BaseItem::~BaseItem() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.BaseItem)
  SharedDtor();
}

void BaseItem::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BaseItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BaseItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BaseItem_descriptor_;
}

const BaseItem& BaseItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

BaseItem* BaseItem::default_instance_ = NULL;

BaseItem* BaseItem::New() const {
  return new BaseItem;
}

void BaseItem::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<BaseItem*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(coin_, friend__);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BaseItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.BaseItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 coin = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &coin_)));
          set_has_coin();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_cash;
        break;
      }

      // optional int32 cash = 2;
      case 2: {
        if (tag == 16) {
         parse_cash:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cash_)));
          set_has_cash();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_exp;
        break;
      }

      // optional int32 exp = 3;
      case 3: {
        if (tag == 24) {
         parse_exp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &exp_)));
          set_has_exp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_friend;
        break;
      }

      // optional int32 friend = 4;
      case 4: {
        if (tag == 32) {
         parse_friend:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &friend__)));
          set_has_friend_();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.BaseItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.BaseItem)
  return false;
#undef DO_
}

void BaseItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.BaseItem)
  // optional int32 coin = 1;
  if (has_coin()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->coin(), output);
  }

  // optional int32 cash = 2;
  if (has_cash()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->cash(), output);
  }

  // optional int32 exp = 3;
  if (has_exp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->exp(), output);
  }

  // optional int32 friend = 4;
  if (has_friend_()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->friend_(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.BaseItem)
}

::google::protobuf::uint8* BaseItem::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.BaseItem)
  // optional int32 coin = 1;
  if (has_coin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->coin(), target);
  }

  // optional int32 cash = 2;
  if (has_cash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->cash(), target);
  }

  // optional int32 exp = 3;
  if (has_exp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->exp(), target);
  }

  // optional int32 friend = 4;
  if (has_friend_()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->friend_(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.BaseItem)
  return target;
}

int BaseItem::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 coin = 1;
    if (has_coin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->coin());
    }

    // optional int32 cash = 2;
    if (has_cash()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cash());
    }

    // optional int32 exp = 3;
    if (has_exp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->exp());
    }

    // optional int32 friend = 4;
    if (has_friend_()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->friend_());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BaseItem::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BaseItem* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BaseItem*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BaseItem::MergeFrom(const BaseItem& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_coin()) {
      set_coin(from.coin());
    }
    if (from.has_cash()) {
      set_cash(from.cash());
    }
    if (from.has_exp()) {
      set_exp(from.exp());
    }
    if (from.has_friend_()) {
      set_friend_(from.friend_());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BaseItem::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BaseItem::CopyFrom(const BaseItem& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseItem::IsInitialized() const {

  return true;
}

void BaseItem::Swap(BaseItem* other) {
  if (other != this) {
    std::swap(coin_, other->coin_);
    std::swap(cash_, other->cash_);
    std::swap(exp_, other->exp_);
    std::swap(friend__, other->friend__);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BaseItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BaseItem_descriptor_;
  metadata.reflection = BaseItem_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PropsItem::kIdFieldNumber;
const int PropsItem::kCountFieldNumber;
#endif  // !_MSC_VER

PropsItem::PropsItem()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.PropsItem)
}

void PropsItem::InitAsDefaultInstance() {
}

PropsItem::PropsItem(const PropsItem& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.PropsItem)
}

void PropsItem::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  count_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PropsItem::~PropsItem() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.PropsItem)
  SharedDtor();
}

void PropsItem::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PropsItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PropsItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PropsItem_descriptor_;
}

const PropsItem& PropsItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

PropsItem* PropsItem::default_instance_ = NULL;

PropsItem* PropsItem::New() const {
  return new PropsItem;
}

void PropsItem::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PropsItem*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(id_, count_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PropsItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.PropsItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_count;
        break;
      }

      // required int32 count = 2;
      case 2: {
        if (tag == 16) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.PropsItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.PropsItem)
  return false;
#undef DO_
}

void PropsItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.PropsItem)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required int32 count = 2;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.PropsItem)
}

::google::protobuf::uint8* PropsItem::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.PropsItem)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required int32 count = 2;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.PropsItem)
  return target;
}

int PropsItem::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required int32 count = 2;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PropsItem::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PropsItem* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PropsItem*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PropsItem::MergeFrom(const PropsItem& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PropsItem::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PropsItem::CopyFrom(const PropsItem& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PropsItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void PropsItem::Swap(PropsItem* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(count_, other->count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PropsItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PropsItem_descriptor_;
  metadata.reflection = PropsItem_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CommonModifyItem::kBasedFieldNumber;
const int CommonModifyItem::kPropsFieldNumber;
#endif  // !_MSC_VER

CommonModifyItem::CommonModifyItem()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.CommonModifyItem)
}

void CommonModifyItem::InitAsDefaultInstance() {
  based_ = const_cast< ::CommonGiftConfig::BaseItem*>(&::CommonGiftConfig::BaseItem::default_instance());
}

CommonModifyItem::CommonModifyItem(const CommonModifyItem& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.CommonModifyItem)
}

void CommonModifyItem::SharedCtor() {
  _cached_size_ = 0;
  based_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonModifyItem::~CommonModifyItem() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.CommonModifyItem)
  SharedDtor();
}

void CommonModifyItem::SharedDtor() {
  if (this != default_instance_) {
    delete based_;
  }
}

void CommonModifyItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonModifyItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonModifyItem_descriptor_;
}

const CommonModifyItem& CommonModifyItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

CommonModifyItem* CommonModifyItem::default_instance_ = NULL;

CommonModifyItem* CommonModifyItem::New() const {
  return new CommonModifyItem;
}

void CommonModifyItem::Clear() {
  if (has_based()) {
    if (based_ != NULL) based_->::CommonGiftConfig::BaseItem::Clear();
  }
  props_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonModifyItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.CommonModifyItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CommonGiftConfig.BaseItem based = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_based()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_props;
        break;
      }

      // repeated .CommonGiftConfig.PropsItem props = 2;
      case 2: {
        if (tag == 18) {
         parse_props:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_props()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_props;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.CommonModifyItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.CommonModifyItem)
  return false;
#undef DO_
}

void CommonModifyItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.CommonModifyItem)
  // optional .CommonGiftConfig.BaseItem based = 1;
  if (has_based()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->based(), output);
  }

  // repeated .CommonGiftConfig.PropsItem props = 2;
  for (int i = 0; i < this->props_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->props(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.CommonModifyItem)
}

::google::protobuf::uint8* CommonModifyItem::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.CommonModifyItem)
  // optional .CommonGiftConfig.BaseItem based = 1;
  if (has_based()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->based(), target);
  }

  // repeated .CommonGiftConfig.PropsItem props = 2;
  for (int i = 0; i < this->props_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->props(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.CommonModifyItem)
  return target;
}

int CommonModifyItem::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .CommonGiftConfig.BaseItem based = 1;
    if (has_based()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->based());
    }

  }
  // repeated .CommonGiftConfig.PropsItem props = 2;
  total_size += 1 * this->props_size();
  for (int i = 0; i < this->props_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->props(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonModifyItem::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonModifyItem* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonModifyItem*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonModifyItem::MergeFrom(const CommonModifyItem& from) {
  GOOGLE_CHECK_NE(&from, this);
  props_.MergeFrom(from.props_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_based()) {
      mutable_based()->::CommonGiftConfig::BaseItem::MergeFrom(from.based());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonModifyItem::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonModifyItem::CopyFrom(const CommonModifyItem& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonModifyItem::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->props())) return false;
  return true;
}

void CommonModifyItem::Swap(CommonModifyItem* other) {
  if (other != this) {
    std::swap(based_, other->based_);
    props_.Swap(&other->props_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonModifyItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonModifyItem_descriptor_;
  metadata.reflection = CommonModifyItem_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CommonModifyItemRate::kIdFieldNumber;
const int CommonModifyItemRate::kRateFieldNumber;
const int CommonModifyItemRate::kItemFieldNumber;
#endif  // !_MSC_VER

CommonModifyItemRate::CommonModifyItemRate()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.CommonModifyItemRate)
}

void CommonModifyItemRate::InitAsDefaultInstance() {
  item_ = const_cast< ::CommonGiftConfig::CommonModifyItem*>(&::CommonGiftConfig::CommonModifyItem::default_instance());
}

CommonModifyItemRate::CommonModifyItemRate(const CommonModifyItemRate& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.CommonModifyItemRate)
}

void CommonModifyItemRate::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  rate_ = 0u;
  item_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonModifyItemRate::~CommonModifyItemRate() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.CommonModifyItemRate)
  SharedDtor();
}

void CommonModifyItemRate::SharedDtor() {
  if (this != default_instance_) {
    delete item_;
  }
}

void CommonModifyItemRate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonModifyItemRate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonModifyItemRate_descriptor_;
}

const CommonModifyItemRate& CommonModifyItemRate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

CommonModifyItemRate* CommonModifyItemRate::default_instance_ = NULL;

CommonModifyItemRate* CommonModifyItemRate::New() const {
  return new CommonModifyItemRate;
}

void CommonModifyItemRate::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CommonModifyItemRate*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(id_, rate_);
    if (has_item()) {
      if (item_ != NULL) item_->::CommonGiftConfig::CommonModifyItem::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonModifyItemRate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.CommonModifyItemRate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_rate;
        break;
      }

      // required uint32 rate = 2;
      case 2: {
        if (tag == 16) {
         parse_rate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rate_)));
          set_has_rate();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_item;
        break;
      }

      // required .CommonGiftConfig.CommonModifyItem item = 3;
      case 3: {
        if (tag == 26) {
         parse_item:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.CommonModifyItemRate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.CommonModifyItemRate)
  return false;
#undef DO_
}

void CommonModifyItemRate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.CommonModifyItemRate)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 rate = 2;
  if (has_rate()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->rate(), output);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 3;
  if (has_item()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->item(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.CommonModifyItemRate)
}

::google::protobuf::uint8* CommonModifyItemRate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.CommonModifyItemRate)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required uint32 rate = 2;
  if (has_rate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->rate(), target);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 3;
  if (has_item()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->item(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.CommonModifyItemRate)
  return target;
}

int CommonModifyItemRate::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 rate = 2;
    if (has_rate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->rate());
    }

    // required .CommonGiftConfig.CommonModifyItem item = 3;
    if (has_item()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->item());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonModifyItemRate::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonModifyItemRate* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonModifyItemRate*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonModifyItemRate::MergeFrom(const CommonModifyItemRate& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_rate()) {
      set_rate(from.rate());
    }
    if (from.has_item()) {
      mutable_item()->::CommonGiftConfig::CommonModifyItem::MergeFrom(from.item());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonModifyItemRate::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonModifyItemRate::CopyFrom(const CommonModifyItemRate& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonModifyItemRate::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_item()) {
    if (!this->item().IsInitialized()) return false;
  }
  return true;
}

void CommonModifyItemRate::Swap(CommonModifyItemRate* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(rate_, other->rate_);
    std::swap(item_, other->item_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonModifyItemRate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonModifyItemRate_descriptor_;
  metadata.reflection = CommonModifyItemRate_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CommonModifyItemGrow::kIdFieldNumber;
const int CommonModifyItemGrow::kLevelFieldNumber;
const int CommonModifyItemGrow::kItemFieldNumber;
#endif  // !_MSC_VER

CommonModifyItemGrow::CommonModifyItemGrow()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.CommonModifyItemGrow)
}

void CommonModifyItemGrow::InitAsDefaultInstance() {
  item_ = const_cast< ::CommonGiftConfig::CommonModifyItem*>(&::CommonGiftConfig::CommonModifyItem::default_instance());
}

CommonModifyItemGrow::CommonModifyItemGrow(const CommonModifyItemGrow& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.CommonModifyItemGrow)
}

void CommonModifyItemGrow::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  level_ = 0u;
  item_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonModifyItemGrow::~CommonModifyItemGrow() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.CommonModifyItemGrow)
  SharedDtor();
}

void CommonModifyItemGrow::SharedDtor() {
  if (this != default_instance_) {
    delete item_;
  }
}

void CommonModifyItemGrow::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonModifyItemGrow::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonModifyItemGrow_descriptor_;
}

const CommonModifyItemGrow& CommonModifyItemGrow::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

CommonModifyItemGrow* CommonModifyItemGrow::default_instance_ = NULL;

CommonModifyItemGrow* CommonModifyItemGrow::New() const {
  return new CommonModifyItemGrow;
}

void CommonModifyItemGrow::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CommonModifyItemGrow*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(id_, level_);
    if (has_item()) {
      if (item_ != NULL) item_->::CommonGiftConfig::CommonModifyItem::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonModifyItemGrow::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.CommonModifyItemGrow)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // required uint32 level = 2;
      case 2: {
        if (tag == 16) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &level_)));
          set_has_level();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_item;
        break;
      }

      // required .CommonGiftConfig.CommonModifyItem item = 3;
      case 3: {
        if (tag == 26) {
         parse_item:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.CommonModifyItemGrow)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.CommonModifyItemGrow)
  return false;
#undef DO_
}

void CommonModifyItemGrow::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.CommonModifyItemGrow)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 level = 2;
  if (has_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->level(), output);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 3;
  if (has_item()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->item(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.CommonModifyItemGrow)
}

::google::protobuf::uint8* CommonModifyItemGrow::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.CommonModifyItemGrow)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required uint32 level = 2;
  if (has_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->level(), target);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 3;
  if (has_item()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->item(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.CommonModifyItemGrow)
  return target;
}

int CommonModifyItemGrow::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 level = 2;
    if (has_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->level());
    }

    // required .CommonGiftConfig.CommonModifyItem item = 3;
    if (has_item()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->item());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonModifyItemGrow::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonModifyItemGrow* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonModifyItemGrow*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonModifyItemGrow::MergeFrom(const CommonModifyItemGrow& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_level()) {
      set_level(from.level());
    }
    if (from.has_item()) {
      mutable_item()->::CommonGiftConfig::CommonModifyItem::MergeFrom(from.item());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonModifyItemGrow::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonModifyItemGrow::CopyFrom(const CommonModifyItemGrow& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonModifyItemGrow::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_item()) {
    if (!this->item().IsInitialized()) return false;
  }
  return true;
}

void CommonModifyItemGrow::Swap(CommonModifyItemGrow* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(level_, other->level_);
    std::swap(item_, other->item_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonModifyItemGrow::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonModifyItemGrow_descriptor_;
  metadata.reflection = CommonModifyItemGrow_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CommonModifyItemNormal::kItemFieldNumber;
#endif  // !_MSC_VER

CommonModifyItemNormal::CommonModifyItemNormal()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.CommonModifyItemNormal)
}

void CommonModifyItemNormal::InitAsDefaultInstance() {
  item_ = const_cast< ::CommonGiftConfig::CommonModifyItem*>(&::CommonGiftConfig::CommonModifyItem::default_instance());
}

CommonModifyItemNormal::CommonModifyItemNormal(const CommonModifyItemNormal& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.CommonModifyItemNormal)
}

void CommonModifyItemNormal::SharedCtor() {
  _cached_size_ = 0;
  item_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonModifyItemNormal::~CommonModifyItemNormal() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.CommonModifyItemNormal)
  SharedDtor();
}

void CommonModifyItemNormal::SharedDtor() {
  if (this != default_instance_) {
    delete item_;
  }
}

void CommonModifyItemNormal::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonModifyItemNormal::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonModifyItemNormal_descriptor_;
}

const CommonModifyItemNormal& CommonModifyItemNormal::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

CommonModifyItemNormal* CommonModifyItemNormal::default_instance_ = NULL;

CommonModifyItemNormal* CommonModifyItemNormal::New() const {
  return new CommonModifyItemNormal;
}

void CommonModifyItemNormal::Clear() {
  if (has_item()) {
    if (item_ != NULL) item_->::CommonGiftConfig::CommonModifyItem::Clear();
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonModifyItemNormal::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.CommonModifyItemNormal)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .CommonGiftConfig.CommonModifyItem item = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.CommonModifyItemNormal)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.CommonModifyItemNormal)
  return false;
#undef DO_
}

void CommonModifyItemNormal::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.CommonModifyItemNormal)
  // required .CommonGiftConfig.CommonModifyItem item = 1;
  if (has_item()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->item(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.CommonModifyItemNormal)
}

::google::protobuf::uint8* CommonModifyItemNormal::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.CommonModifyItemNormal)
  // required .CommonGiftConfig.CommonModifyItem item = 1;
  if (has_item()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->item(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.CommonModifyItemNormal)
  return target;
}

int CommonModifyItemNormal::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .CommonGiftConfig.CommonModifyItem item = 1;
    if (has_item()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->item());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonModifyItemNormal::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonModifyItemNormal* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonModifyItemNormal*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonModifyItemNormal::MergeFrom(const CommonModifyItemNormal& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_item()) {
      mutable_item()->::CommonGiftConfig::CommonModifyItem::MergeFrom(from.item());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonModifyItemNormal::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonModifyItemNormal::CopyFrom(const CommonModifyItemNormal& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonModifyItemNormal::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_item()) {
    if (!this->item().IsInitialized()) return false;
  }
  return true;
}

void CommonModifyItemNormal::Swap(CommonModifyItemNormal* other) {
  if (other != this) {
    std::swap(item_, other->item_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonModifyItemNormal::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonModifyItemNormal_descriptor_;
  metadata.reflection = CommonModifyItemNormal_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CommonModifyItemSimple::kIdFieldNumber;
const int CommonModifyItemSimple::kItemFieldNumber;
#endif  // !_MSC_VER

CommonModifyItemSimple::CommonModifyItemSimple()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonGiftConfig.CommonModifyItemSimple)
}

void CommonModifyItemSimple::InitAsDefaultInstance() {
  item_ = const_cast< ::CommonGiftConfig::CommonModifyItem*>(&::CommonGiftConfig::CommonModifyItem::default_instance());
}

CommonModifyItemSimple::CommonModifyItemSimple(const CommonModifyItemSimple& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommonGiftConfig.CommonModifyItemSimple)
}

void CommonModifyItemSimple::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  item_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommonModifyItemSimple::~CommonModifyItemSimple() {
  // @@protoc_insertion_point(destructor:CommonGiftConfig.CommonModifyItemSimple)
  SharedDtor();
}

void CommonModifyItemSimple::SharedDtor() {
  if (this != default_instance_) {
    delete item_;
  }
}

void CommonModifyItemSimple::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonModifyItemSimple::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommonModifyItemSimple_descriptor_;
}

const CommonModifyItemSimple& CommonModifyItemSimple::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CommonGiftConfig_2eproto();
  return *default_instance_;
}

CommonModifyItemSimple* CommonModifyItemSimple::default_instance_ = NULL;

CommonModifyItemSimple* CommonModifyItemSimple::New() const {
  return new CommonModifyItemSimple;
}

void CommonModifyItemSimple::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    id_ = 0u;
    if (has_item()) {
      if (item_ != NULL) item_->::CommonGiftConfig::CommonModifyItem::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CommonModifyItemSimple::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonGiftConfig.CommonModifyItemSimple)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_item;
        break;
      }

      // required .CommonGiftConfig.CommonModifyItem item = 2;
      case 2: {
        if (tag == 18) {
         parse_item:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonGiftConfig.CommonModifyItemSimple)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonGiftConfig.CommonModifyItemSimple)
  return false;
#undef DO_
}

void CommonModifyItemSimple::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonGiftConfig.CommonModifyItemSimple)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 2;
  if (has_item()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->item(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonGiftConfig.CommonModifyItemSimple)
}

::google::protobuf::uint8* CommonModifyItemSimple::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommonGiftConfig.CommonModifyItemSimple)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required .CommonGiftConfig.CommonModifyItem item = 2;
  if (has_item()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->item(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonGiftConfig.CommonModifyItemSimple)
  return target;
}

int CommonModifyItemSimple::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required .CommonGiftConfig.CommonModifyItem item = 2;
    if (has_item()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->item());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonModifyItemSimple::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CommonModifyItemSimple* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CommonModifyItemSimple*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommonModifyItemSimple::MergeFrom(const CommonModifyItemSimple& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_item()) {
      mutable_item()->::CommonGiftConfig::CommonModifyItem::MergeFrom(from.item());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CommonModifyItemSimple::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonModifyItemSimple::CopyFrom(const CommonModifyItemSimple& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonModifyItemSimple::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_item()) {
    if (!this->item().IsInitialized()) return false;
  }
  return true;
}

void CommonModifyItemSimple::Swap(CommonModifyItemSimple* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(item_, other->item_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CommonModifyItemSimple::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommonModifyItemSimple_descriptor_;
  metadata.reflection = CommonModifyItemSimple_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace CommonGiftConfig

// @@protoc_insertion_point(global_scope)
